export const cloudConnectDict = {
  EN: {
    title: "Cloud Connect Logs",
    subtitle: "Monitor incoming requests to your Cloud Connect endpoints.",
    searchPlaceholder: "Search logs...",
    timeRange: {
      last24h: "Last 24 Hours",
    },
    columns: {
      time: "Timestamp",
      status: "Status",
      description: "Description",
      domain: "Endpoint Domain",
      path: "Endpoint Path",
      latency: "Latency (ms)",
      actions: "Actions",
    },
    table: {
      loading: "Loading logs...",
      noData: "No logs found.",
      rowsPerPage: "Rows per page:",
      of: "of",
    },
    modal: {
      title: "Log Details",
      close: "Close",
    },
    flyout: {
      title: "Log Details",
      tabTable: "Table",
      tabJson: "JSON",
      searchPlaceholder: "Search fields...",
      field: "Field",
      value: "Value",
      copyJson: "Copy JSON",
      copied: "Copied!",
    },
    registerBtn: "Register to Cloud",
    registerModal: {
      title: "Register to Cloud",
      subtitle:
        "Connect your local environment to Please Protect Cloud services.",
      endpoint: "Connect Endpoint",
      endpointDesc: "The URL of the remote Please Protect endpoint.",
      endpointPlaceholder: "e.g., https://api.please-protect.com/...",
      key: "Connect Key",
      keyDesc: "Authentication key for secure sync.",
      keyPlaceholder: "Enter your secure connect key",
      sync: "Cloud Sync",
      syncDesc: "Enable or disable data synchronization to the cloud.",
      enabled: "Enabled",
      disabled: "Disabled",
      edit: "Edit",
      save: "Save",
      saving: "Saving...",
      cancel: "Cancel",
      saveSuccess: "Configuration saved successfully",
      saveError: "Failed to save configuration",
    },
  },
  TH: {
    title: "บันทึก Cloud Connect",
    subtitle: "ตรวจสอบคำขอที่เข้ามายังปลายทาง Cloud Connect ของคุณ",
    searchPlaceholder: "ค้นหาข้อมูล...",
    timeRange: {
      last24h: "24 ชั่วโมงที่ผ่านมา",
    },
    columns: {
      time: "เวลา",
      status: "สถานะ",
      description: "รายละเอียด",
      domain: "โดเมนปลายทาง",
      path: "เส้นทางปลายทาง",
      latency: "เวลาแฝง (ms)",
      actions: "การดำเนินการ",
    },
    table: {
      loading: "กำลังโหลดข้อมูล...",
      noData: "ไม่พบข้อมูล",
      rowsPerPage: "แถวต่อหน้า:",
      of: "จาก",
    },
    modal: {
      title: "รายละเอียด",
      close: "ปิด",
    },
    flyout: {
      title: "รายละเอียด Log",
      tabTable: "ตาราง",
      tabJson: "JSON",
      searchPlaceholder: "ค้นหาข้อมูล...",
      field: "ฟิลด์",
      value: "ข้อมูล",
      copyJson: "คัดลอก JSON",
      copied: "คัดลอกแล้ว!",
    },
    registerBtn: "เชื่อมต่อคลาวด์",
    registerModal: {
      title: "ลงทะเบียนกับคลาวด์",
      subtitle: "เชื่อมต่อสภาพแวดล้อมของคุณกับบริการ Please Protect Cloud",
      endpoint: "Endpoint การเชื่อมต่อ",
      endpointDesc: "URL ของเซิร์ฟเวอร์ Please Protect รีโมท",
      endpointPlaceholder: "ต.ย. https://api.please-protect.com/...",
      key: "กุญแจเชื่อมต่อ (Connect Key)",
      keyDesc: "คีย์ยืนยันตัวตนสำหรับการซิงค์ข้อมูลอย่างปลอดภัย",
      keyPlaceholder: "กรอกกุญแจเชื่อมต่อของคุณ",
      sync: "ซิงโครไนซ์กับคลาวด์",
      syncDesc: "เปิดหรือปิดระบบพุชข้อมูลขึ้นคลาวด์",
      enabled: "เปิดใช้งานแล้ว",
      disabled: "ปิดใช้งานอยู่",
      edit: "แก้ไข",
      save: "บันทึก",
      saving: "กำลังบันทึก...",
      cancel: "ยกเลิก",
      saveSuccess: "บันทึกการตั้งค่าสำเร็จ",
      saveError: "ไม่สามารถบันทึกการตั้งค่าได้",
    },
  },
};
