export const alertRulesDict = {
  EN: {
    title: "Prometheus Rules",
    subtitle: "Browse all rule groups and alerting rules currently evaluated in the system",
    searchPlaceholder: "Filter by rule name, query, labels, or group",
    stateFilter: "Filter by rule state",
    refresh: "Refresh",
    allStates: "All states",
    loading: "Loading rules...",
    loadError: "Failed to load rules",
    noData: "No rules found",
    rowsPerPage: "Rows per page:",
    of: "of",
    columns: {
      state: "State",
      name: "Rule",
      severity: "Severity",
      duration: "Duration",
      health: "Health",
      type: "Type",
      summary: "Summary",
      query: "Query",
    },
    labels: {
      file: "File",
      alerts: "Active alerts",
      lastEval: "Last evaluation",
    },
  },
  TH: {
    title: "Prometheus Rules",
    subtitle: "แสดงกลุ่มกฎและรายการกฎที่ระบบกำลังประเมินทั้งหมด",
    searchPlaceholder: "ค้นหาด้วยชื่อกฎ query labels หรือชื่อกลุ่ม",
    stateFilter: "กรองตามสถานะกฎ",
    refresh: "รีเฟรช",
    allStates: "ทุกสถานะ",
    loading: "กำลังโหลดกฎ...",
    loadError: "โหลดกฎไม่สำเร็จ",
    noData: "ไม่พบข้อมูลกฎ",
    rowsPerPage: "จำนวนแถวต่อหน้า:",
    of: "จาก",
    columns: {
      state: "สถานะ",
      name: "กฎ",
      severity: "ความรุนแรง",
      duration: "ระยะเวลา",
      health: "สุขภาพ",
      type: "ประเภท",
      summary: "สรุป",
      query: "Query",
    },
    labels: {
      file: "ไฟล์",
      alerts: "Alerts ที่ active",
      lastEval: "ประเมินล่าสุด",
    },
  },
};

export type AlertRulesDict = typeof alertRulesDict.EN;
