export const alertChannelDict = {
  EN: {
    title: "Notifications Channel",
    createTitle: "Create Notification Channel",
    updateTitle: "Update Notification Channel",
    subHeader: "Manage your notification channels",
    createSubHeader: "Set up a new notification channel for alerts.",
    updateSubHeader: "Edit channel details and save changes.",
    channelInfoTitle: "Channel Information",
    searchPlaceholder: "Search channels...",
    columns: {
      channelName: "Channel Name",
      description: "Description",
      tags: "Tags",
      type: "Type",
      status: "Status",
      action: "Action",
      discordWebhookUrl: "Discord Webhook URL",
    },
    buttons: {
      add: "Add",
      delete: "Delete",
      enable: "Enable Channel",
      disable: "Disable Channel",
      cancel: "Cancel",
      confirm: "Confirm",
      discord: "Discord",
    },
    status: {
      enabled: "Enabled",
      disabled: "Disabled",
    },
    loading: "Loading...",
    noData: "No notification channels found",
    rowsPerPage: "Rows per page:",
    of: "of",
    confirm: {
      enableTitle: "Enable Channel",
      enableMessage:
        "Are you sure you want to enable this notification channel?",
      disableTitle: "Disable Channel",
      disableMessage:
        "Are you sure you want to disable this notification channel?",
      deleteTitle: "Delete Channel",
      deleteMessage:
        "Are you sure you want to delete this notification channel?",
    },
    toast: {
      enableSuccess: "Channel enabled successfully",
      enableError: "Failed to enable channel",
      disableSuccess: "Channel disabled successfully",
      disableError: "Failed to disable channel",
      deleteSuccess: "Channel deleted successfully",
      deleteError: "Failed to delete channel",
      fetchError: "Failed to load channels",
    },
    validation: {
      channelNameRequired: "Channel name is required",
      channelNameMax: "Channel name must be less than 100 characters",
      descriptionRequired: "Description is required",
      descriptionMax: "Description must be less than 500 characters",
      discordUrlRequired: "Discord webhook URL is required",
      discordUrlInvalid: "Invalid URL format",
      tagsInvalid: "Invalid tag format. Tags should be comma-separated.",
    },
  },
  TH: {
    title: "ช่องทางการแจ้งเตือน",
    createTitle: "สร้างช่องทางการแจ้งเตือน",
    updateTitle: "แก้ไขช่องทางการแจ้งเตือน",
    subHeader: "จัดการช่องทางการแจ้งเตือนของคุณ",
    createSubHeader: "ตั้งค่าช่องทางใหม่สำหรับการแจ้งเตือน",
    updateSubHeader: "แก้ไขรายละเอียดช่องทางและบันทึกการเปลี่ยนแปลง",
    channelInfoTitle: "ข้อมูลช่องทาง",
    searchPlaceholder: "ค้นหาช่องทาง...",
    columns: {
      channelName: "ชื่อช่องทาง",
      description: "คำอธิบาย",
      tags: "แท็ก",
      type: "ประเภท",
      status: "สถานะ",
      action: "การดำเนินการ",
      discordWebhookUrl: "Discord Webhook URL",
    },
    buttons: {
      add: "เพิ่ม",
      delete: "ลบ",
      enable: "เปิดใช้งานช่องทาง",
      disable: "ปิดใช้งานช่องทาง",
      cancel: "ยกเลิก",
      confirm: "ยืนยัน",
      discord: "Discord",
    },
    status: {
      enabled: "เปิดใช้งาน",
      disabled: "ปิดใช้งาน",
    },
    loading: "กำลังโหลด...",
    noData: "ไม่พบช่องทางการแจ้งเตือน",
    rowsPerPage: "จำนวนแถวต่อหน้า:",
    of: "จาก",
    confirm: {
      enableTitle: "เปิดใช้งานช่องทาง",
      enableMessage: "คุณแน่ใจหรือไม่ว่าต้องการเปิดใช้งานช่องทางนี้?",
      disableTitle: "ปิดใช้งานช่องทาง",
      disableMessage: "คุณแน่ใจหรือไม่ว่าต้องการปิดใช้งานช่องทางนี้?",
      deleteTitle: "ลบช่องทาง",
      deleteMessage: "คุณแน่ใจหรือไม่ว่าต้องการลบช่องทางนี้?",
    },
    toast: {
      enableSuccess: "เปิดใช้งานช่องทางสำเร็จ",
      enableError: "ไม่สามารถเปิดใช้งานช่องทางได้",
      disableSuccess: "ปิดใช้งานช่องทางสำเร็จ",
      disableError: "ไม่สามารถปิดใช้งานช่องทางได้",
      deleteSuccess: "ลบช่องทางสำเร็จ",
      deleteError: "ไม่สามารถลบช่องทางได้",
      fetchError: "ไม่สามารถโหลดข้อมูลช่องทางได้",
    },
    validation: {
      channelNameRequired: "กรุณาระบุชื่อช่องทาง",
      channelNameMax: "ชื่อช่องทางต้องมีความยาวไม่เกิน 100 ตัวอักษร",
      descriptionRequired: "กรุณาระบุคำอธิบาย",
      descriptionMax: "คำอธิบายต้องมีความยาวไม่เกิน 500 ตัวอักษร",
      discordUrlRequired: "กรุณาระบุ Discord webhook URL",
      discordUrlInvalid: "รูปแบบ URL ไม่ถูกต้อง",
      tagsInvalid: "รูปแบบแท็กไม่ถูกต้อง กรุณาคั่นแต่ละแท็กด้วยลูกน้ำ",
    },
  },
};

export type AlertChannelDict = typeof alertChannelDict.EN;
