export const geoipAttackMapDict = {
  EN: {
    title: "GeoIP Attack Map",
    subtitle: "Real-time global attack visualization",
    filterDataset: "Dataset",
    filterSrcCountry: "Source Country",
    filterDstCountry: "Dest. Country",
    allDatasets: "All Datasets",
    allCountries: "All Countries",
    totalAttacks: "Total",
    activeArcs: "Active",
    connecting: "Connecting...",
    live: "Live",
    disconnected: "Disconnected",
    noData: "Waiting for attack events...",
  },
  TH: {
    title: "แผนที่การโจมตี GeoIP",
    subtitle: "การแสดงผลการโจมตีแบบเรียลไทม์",
    filterDataset: "Dataset",
    filterSrcCountry: "ประเทศต้นทาง",
    filterDstCountry: "ประเทศปลายทาง",
    allDatasets: "ทุก Dataset",
    allCountries: "ทุกประเทศ",
    totalAttacks: "ทั้งหมด",
    activeArcs: "กำลังแสดง",
    connecting: "กำลังเชื่อมต่อ...",
    live: "ไลฟ์",
    disconnected: "ขาดการเชื่อมต่อ",
    noData: "กำลังรอข้อมูลการโจมตี...",
  },
} as const;
