export const interfaceNetworkDict = {
  EN: {
    title: "Interfaces",
    subtitle:
      "Network interfaces 4-port layout",
    panelTitle: "NETWORK SWITCH 4-PORT",
    power: "PWR",
    system: "SYS",
    loading: "Loading interfaces...",
    loadError: "Failed to load interfaces.",
    retry: "Retry",
    emptySlot: "Empty slot",
    connected: "Connected",
    notConnected: "Not connected",
    disabled: "Disabled",
    activeTraffic: "Active traffic",
    enabledIdle: "Enabled (idle)",
    noPhysicalInterface: "No physical interface detected",
    noTrafficMetrics: "No traffic metrics",
    ip: "IP",
    mac: "MAC",
    rxData: "Rx Data",
    txData: "Tx Data",
    rxPackets: "Rx Pkts",
    txPackets: "Tx Pkts",
    disableInterface: "Disable interface",
    enableInterface: "Enable interface",
    updating: "Updating...",
    disableConfirmTitle: "Disable interface",
    disableConfirmMessage:
      "Are you sure you want to disable this interface slot?",
    disableConfirmButton: "Disable",
    cancel: "Cancel",
    mustKeepOneEnabled: "At least one interface must remain enabled.",
    toggleFailed: "Failed to update interface status.",
    enabledSuccess: "enabled",
    disabledSuccess: "disabled",
  },
  TH: {
    title: "อินเทอร์เฟซ",
    subtitle:
      "แสดง Network Interface แบบ 4 พอร์ต",
    panelTitle: "สวิตช์เครือข่าย 4 พอร์ต",
    power: "PWR",
    system: "SYS",
    loading: "กำลังโหลดอินเทอร์เฟซ...",
    loadError: "ไม่สามารถโหลดข้อมูลอินเทอร์เฟซได้",
    retry: "ลองใหม่",
    emptySlot: "ช่องว่าง",
    connected: "เชื่อมต่ออยู่",
    notConnected: "ยังไม่เชื่อมต่อ",
    disabled: "ปิดใช้งาน",
    activeTraffic: "มีทราฟฟิก",
    enabledIdle: "เปิดใช้งาน (ไม่มีทราฟฟิก)",
    noPhysicalInterface: "ไม่พบ physical interface",
    noTrafficMetrics: "ไม่มีข้อมูลทราฟฟิก",
    ip: "IP",
    mac: "MAC",
    rxData: "ข้อมูลรับ",
    txData: "ข้อมูลส่ง",
    rxPackets: "แพ็กเก็ตรับ",
    txPackets: "แพ็กเก็ตส่ง",
    disableInterface: "ปิดการใช้งานอินเทอร์เฟซ",
    enableInterface: "เปิดการใช้งานอินเทอร์เฟซ",
    updating: "กำลังอัปเดต...",
    disableConfirmTitle: "ยืนยันปิดการใช้งาน",
    disableConfirmMessage: "ต้องการปิดการใช้งานอินเทอร์เฟซช่องนี้หรือไม่",
    disableConfirmButton: "ปิดการใช้งาน",
    cancel: "ยกเลิก",
    mustKeepOneEnabled: "ต้องมีอินเทอร์เฟซที่เปิดใช้งานอย่างน้อย 1 ช่อง",
    toggleFailed: "ไม่สามารถอัปเดตสถานะอินเทอร์เฟซได้",
    enabledSuccess: "เปิดใช้งานแล้ว",
    disabledSuccess: "ปิดใช้งานแล้ว",
  },
};

export type InterfaceNetworkDict =
  (typeof interfaceNetworkDict)[keyof typeof interfaceNetworkDict];
